### ISSUE TITLE
DOCS: Missing setup steps.

### ISSUE THREAD

**Issue by wpoosanguansit** [fsanaulla/chronicler#120]
Hi,

I am trying out the library and I ran into getting the code to compile.  From the import:

import com.github.fsanaulla.chronicler.ahc.io.{AhcIOClient, InfluxIO}
import com.github.fsanaulla.macros.annotations.{field, tag, timestamp}
import com.github.fsanaulla.core.model.InfluxFormatter
import com.github.fsanaulla.chronicler.ahc.io.api.Measurement

[error] object macros is not a member of package com.github.fsanaulla
[error] import com.github.fsanaulla.macros.annotations.{field, tag, timestamp}
[error]                             ^
[error] object core is not a member of package com.github.fsanaulla
[error] import com.github.fsanaulla.core.model.InfluxFormatter

macros and core are not recognized.  Is there any setup steps that are not listed in the getting started doc that I would need to follow.  Thank you for your help.

**Comment by fsanaulla** [comment]
Hello, @wpoosanguansit.

I forget to update the example. Try to change: `import com.github.fsanaulla.macros` -> `import com.github.fsanaulla.chronicler.macros` and `com.github.fsanaulla.core` -> `com.github.fsanaulla.chronicler.core`. I'm also working on exmaples that will  be located as a separate module.

**Comment by wpoosanguansit** [comment]
Thank you @fsanaulla.  I do have the follow up questions:  where is the InfluxDuration as in import com.github.fsanaulla.core.utils.InfluxDuration._? this seems to be moved. also where do i import Macros from? as in Macros.format. Thanks for your help.

**Comment by fsanaulla** [comment]
@wpoosanguansit can I close this issue?

**Comment by wpoosanguansit** [comment]
Definitely yes.  Thank you for your help.

**Comment by fsanaulla** [comment]
@wpoosanguansit no problem :)
