### ISSUE TITLE
Memory issue with large data sets

### ISSUE THREAD

**Issue by tezhm** [fsanaulla/chronicler#186]
Querying for result which returns 1000000 rows seems to require over 2GB of ram from JVM. I've tried tweaking JVM settings to get following query to even return a result within ~15 minutes but no luck.

Following query works fine with scala-influxdb-client and I get a result within 10 seconds:

```
    val query = influxIo.database("test_database").readJson("SELECT * FROM some_table ORDER BY time DESC LIMIT 1000000", Epochs.Nanoseconds)
    Await.result(query, 1000.seconds) match {
      case Left(e) => throw e
      case Right(result) => promise success result
    }
```

**Comment by fsanaulla** [comment]
Hello @tez-m, which backend you use?

**Comment by tez-m** [comment]
Sorry for late reply. I am using the AhcIOClient.

**Comment by fsanaulla** [comment]
Publishing `0.6.0` release, it should be available soon. 
@tez-m can you try it with 0.6.0?

**Comment by fsanaulla** [comment]
Hello, @tez-m did you try it?

**Comment by tez-m** [comment]
Hey @fsanaulla, sorry I'm not working on scala at the moment so haven't had a chance to confirm.

**Comment by fsanaulla** [comment]
Reopen if needed
