### ISSUE TITLE
InfluxConfig - input address

### ISSUE THREAD

**Issue by couchds** [fsanaulla/chronicler#204]
The following will give an http error (using this in Apache Spark, along with chronicler-spark):
```
import com.github.fsanaulla.chronicler.urlhttp.shared.InfluxConfig
implicit lazy val influxConf: InfluxConfig = InfluxConfig("http://12.345.67.89", 8086, ...)
```
while the correct line is:
```
import com.github.fsanaulla.chronicler.urlhttp.shared.InfluxConfig
implicit lazy val influxConf: InfluxConfig = InfluxConfig("12.345.67.89", 8086, ...)
```
The reason being that the URL class within urlhttp prepends 'http' to the host.
modules/url/shared/src/main/scala/com/github/fsanaulla/chronicler/urlhttp/shared/Url.scala

I think either this should be more evident to the user (i.e documentation of the InfluxConfig class), or the user should specify the entire address.

**Comment by fsanaulla** [comment]
Solved in #205. Protocol specification forced to user
