### ISSUE TITLE
ALPAKKA: Integration to alpakka?

### ISSUE THREAD

**Issue by fsanaulla** [fsanaulla/chronicler#46]

**Comment by fsanaulla** [comment]
Hi @ioreskovic.

Sounds great! I very appreciated in your help. Should I assign it to you?
At the moment I preparing release 0.4.0. That will provide few useful things for it. 
So in a while, you can implement alpakka integration from the latest `chronicler` release.

What do you think about it?
Thank you!

**Comment by ioreskovic** [comment]
Hi @fsanaulla!

Don't assign it to me just yet, I need to check out some things before :D

I'll try to fiddle around with `chronicler` API this weekend to get a feel for it, and try to come up with a draft of what I'd need to integrate it with Alpakka (I've never done it before).

After that, you can give me some guidelines/tips which I could follow, and then I could start.
Is this OK with you?

**Comment by fsanaulla** [comment]
@ioreskovic Yep, sure. Take your time to be comfortable with it. 
Feel free to ask me any question. 
For more latest API watch `0.4.0` branch, it will be published soon. Also, I will update all necessary documentation, to simplify your survey!

**Comment by fsanaulla** [comment]
https://github.com/akka/alpakka/pull/1680
