### ISSUE TITLE
MACROS: How to save object + timestamp with macro?

### ISSUE THREAD

**Issue by AurelienEnr** [fsanaulla/chronicler#52]
Hello,

Basically I would like to put measurement with any given timestamp. (eg saving past data)
I also want it to be within the scala object when I save it and when I fetch it from Influx, i.e.:

```scala

import com.github.fsanaulla.core.model.{InfluxReader, InfluxWriter}
import com.github.fsanaulla.macros.annotations.{field, tag}
import jawn.ast.JArray

case class Foo(@tag product: String, @field qty: Int, time: Long) {

  def influxOneLiner: String = {
    s"${Foo.measurementName},product=$product qty=$qty $time"
  }

}

object Foo {

  val measurementName = "foos"

  implicit val writer = new InfluxWriter[Foo] {
    def write(fe: Foo): String = fe.influxOneLiner
  }

  implicit val reader = new InfluxReader[Foo] {
    def read(js: JArray): Foo = Foo(time=js.get(0).asLong, product=js.get(1).asString, qty=js.get(2).asInt)
  }

}
```

Unless I am mistaken I feel like I cannot use Macros and I can only use "writeNative" but it seems weird to me not to be able to use the timestamp, so I think I am missing something.
Either I write a parser or I duplicate the timestamp by having a field time:

```scala
case class Foo(@tag product: String, @field qty: Int, @field time: Long)
```

Anyway, thanks for your work :)

EDIT:
The "Point API" allows setting a "time" when saving data but there still the parsing that I guess needs to be manual.

EDIT 2:
Finished Foo example.

**Comment by fsanaulla** [comment]
@AurelienEnr Thank you for your issue. Will implement it ASAP.

**Comment by fsanaulla** [comment]
@AurelienEnr added support for `@timestamp` annotation #55. For more details see [documentation](https://github.com/fsanaulla/chronicler/blob/master/docs/macros.md).

**Comment by fsanaulla** [comment]
@AurelienEnr 0.2.3. will be available in a few hours.

**Comment by AurelienEnr** [comment]
Thank you.
I think there might be an issue though:
- Writing works
  - [your test](https://github.com/fsanaulla/chronicler/blob/5f7ccafb23a178bd6a56ff730dca7b243167433a/macros/src/test/scala/com/github/fsanaulla/macros/MacroWriterSpec.scala)
- **Reading does not work for me**
  - [your test](https://github.com/fsanaulla/chronicler/blob/5f7ccafb23a178bd6a56ff730dca7b243167433a/macros/src/test/scala/com/github/fsanaulla/macros/MacroFormatterSpec.scala)
    - your test receives a timestamp as a String but I think I get a number since I have the following error:

> expected string, got number
>
> jawn.ast.WrongValueException: expected string, got number
>
>	at jawn.ast.JValue.asString(JValue.scala:25)

**Should not your test be as follow?**
```scala
  "Macros.format" should "read with None" in {
    fm
      .read(JArray(Array(JNum(1438715114318570484L), JNum(4), JString("Fz"), JNull)))
      .shouldEqual(Test("Fz", None, 4, 1438715114318570484L))
}
```

By the way, when I read using
```scala
db.readJs(s"SELECT * FROM ${Foo.measurementName}")
```
I get:
> [10000000,"p",-1]

Annex:
```scala
import com.github.fsanaulla.core.model.{InfluxFormatter, InfluxReader, InfluxWriter}
import com.github.fsanaulla.macros.Macros
import com.github.fsanaulla.macros.annotations.{field, tag, timestamp}


case class Foo(@tag product: String, @field qty: Int, @timestamp time: Long) {

  def influxOneLiner: String = {
    s"${Foo.measurementName},product=$product qty=$qty $time"
  }

}

object Foo {

  val measurementName = "foos123456789"

  implicit val reader: InfluxReader[Foo] = Macros.reader[Foo]
  implicit val writer: InfluxWriter[Foo] = Macros.writer[Foo]
  implicit val fmt: InfluxFormatter[Foo] = Macros.format[Foo]

}
```

**Comment by AurelienEnr** [comment]
Your other tests do work (I guess, I have not tested them) with a Timestamp as a String.
So I guess that there might be a missing piece with "@timestamp" so it handles Long vs String.
(Sorry I have not dived enough in your code to check this, I may do this later)

**Comment by fsanaulla** [comment]
@AurelienEnr influx return time field in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) date time format.

See this examples:
- [This one](https://docs.influxdata.com/influxdb/v1.5/query_language/data_exploration/#examples-12)
- [And this one](https://docs.influxdata.com/influxdb/v1.5/guides/querying_data/#querying-data-with-the-http-api).

Will check your example.

**Comment by AurelienEnr** [comment]
I guess Influx can return in both kind of format?
Because my previous reader worked with a Long.

```scala
implicit val reader = new InfluxReader[Foo] {
    def read(js: JArray): Foo = Foo(time=js.get(0).asLong, product=js.get(1).asString, qty=js.get(2).asInt)
  }
```

**Comment by fsanaulla** [comment]
The official documentation said, that by the HTTP can return only RFC date time string, [link](https://www.influxdata.com/blog/tldr-influxdb-tech-tips-november-10-2016/), take a look on **configure returned timestamp** section. Also [this](https://docs.influxdata.com/influxdb/v1.5/write_protocols/line_protocol_tutorial/#timestamp).

Under the hood, the new macro reader, first of all, parse input string to `java.time.Instant` and then convert it to **Long**.

If you can please provide an example of code that's fails.  So I can reproduce it and detect the issue.

Thank you for a reporting this issue.

**Comment by AurelienEnr** [comment]
https://github.com/AurelienEnr/chronicler_foo

Basically I am able to:
- write objects
- read untyped objects

I fail:
- reading typed objects with and without **Macro**

ps: My handling of *Future* is probably a lot dirty, I am sorry about that ;)

**Comment by fsanaulla** [comment]
Wow, great example. Thank you. Will take a look at it today.

**Comment by fsanaulla** [comment]
@AurelienEnr did you had a chance to look at my PR on your foo project?

**Comment by AurelienEnr** [comment]
Sorry I had not receive a notification warning me.
Thank you.
