### ISSUE TITLE
CORE: String and Integer field are not handled correctly

### ISSUE THREAD

**Issue by AurelienEnr** [fsanaulla/chronicler#58]
# Issue
Saving a string field ends up in saving the boolean **false** instead.

```scala
    Point(measurement = "foo")
      .addTag("a", "b")
      .addField("c", "d")
      .serialize
// Persisted in InfluxDB: c=false, found this using a SELECT * FROM foo
```

# Influx documentation
https://docs.influxdata.com/influxdb/v1.5/write_protocols/line_protocol_tutorial/

Strings - double quote string field values (more on quoting in Line Protocol below).

Store the field value too warm as a string:

```
weather,location=us-midwest temperature="too warm" 1465839830100400200
```

Integers - append an i to the field value to tell InfluxDB to store the number as an integer.

Store the field value 82 as an integer:

```
weather,location=us-midwest temperature=82i 1465839830100400200
```

# Change to be made imho
Unless I have a different version than you I think there are quotes missing around value in:
[InfluxPoint](https://github.com/fsanaulla/chronicler/blob/6f7f861fdde3f81d0306bb0bc752a7c78b65c0dd/core/src/main/scala/com/github/fsanaulla/core/model/InfluxPoint.scala)

```scala
case class StringField(key: String, value: String) extends InfluxField {
  override def toString: String = key + "=" + value
}

case class IntField(key: String, value: Int) extends InfluxField {
  override def toString: String = key + "=" + value
}
```
Should be in my opinion:
```scala
case class StringField(key: String, value: String) extends InfluxField {
  override def toString: String = s"""$key="$value""""
}

case class IntField(key: String, value: Int) extends InfluxField {
  override def toString: String = key + "=" + value + "i"
}
```

# Test using docker (no scala)

The behavior is slightly different than when using your project, using your project saves an object with a field = **false**, using InfluxDB shell client does not save anything and returns an error.

[docker source](https://hub.docker.com/_/influxdb/)
```bash
mkdir -p data/influxdb
influxdb_data_dir=$(pwd)/data/influxdb
docker run -p 8086:8086 -v $influxdb_data_dir:/var/lib/influxdb influxdb

docker exec -it <influxdb_container_id> influx
# InfluxDB shell

# use some database
INSERT foo,product=p1 qty="abc"
SELECT * FROM foo
#time                product qty
#----                ------- ---
#1527694338836177441 p1      abc

INSERT foo,product=p1 qty=abc
# ERR: {"error":"unable to parse 'foo,product=p1 qty=abc': invalid boolean"}
SELECT * FROM foo
#time                product qty
#----                ------- ---
#1527694338836177441 p1      abc
```

Thanks :)

**Comment by AurelienEnr** [comment]
Thank you,

btw my previous post have few mistake, the only one I manage to save was one with the string "f" which was interpreted as a boolean False.
So actually it had the same behavior as my test in InfluxDB shell.

**Comment by fsanaulla** [comment]
@AurelienEnr ping me if the issue still appears. Thank you for your contribution.
